// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/br/ufs/dcomp/ChatRabbitMQ/ProtoBuf.proto

package br.ufs.dcomp.ChatRabbitMQ;

public final class ProtoBuf {
  private ProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatRabbitMQ.Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     */
    java.lang.String getEmissor();
    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmissorBytes();

    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     */
    java.lang.String getHora();
    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     */
    com.google.protobuf.ByteString
        getHoraBytes();

    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     */
    java.lang.String getGrupo();
    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     */
    com.google.protobuf.ByteString
        getGrupoBytes();

    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    java.util.List<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo> 
        getConteudoList();
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo getConteudo(int index);
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    int getConteudoCount();
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    java.util.List<? extends br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder> 
        getConteudoOrBuilderList();
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder getConteudoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ChatRabbitMQ.Mensagem}
   */
  public  static final class Mensagem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatRabbitMQ.Mensagem)
      MensagemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mensagem() {
      emissor_ = "";
      data_ = "";
      hora_ = "";
      grupo_ = "";
      conteudo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              emissor_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              hora_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              grupo_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                conteudo_ = new java.util.ArrayList<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo>();
                mutable_bitField0_ |= 0x00000010;
              }
              conteudo_.add(
                  input.readMessage(br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          conteudo_ = java.util.Collections.unmodifiableList(conteudo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Mensagem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.class, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.Builder.class);
    }

    private int bitField0_;
    public static final int EMISSOR_FIELD_NUMBER = 1;
    private volatile java.lang.Object emissor_;
    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     */
    public java.lang.String getEmissor() {
      java.lang.Object ref = emissor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emissor_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmissorBytes() {
      java.lang.Object ref = emissor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emissor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HORA_FIELD_NUMBER = 3;
    private volatile java.lang.Object hora_;
    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     */
    public java.lang.String getHora() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hora_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHoraBytes() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRUPO_FIELD_NUMBER = 4;
    private volatile java.lang.Object grupo_;
    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     */
    public java.lang.String getGrupo() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grupo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGrupoBytes() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grupo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEUDO_FIELD_NUMBER = 5;
    private java.util.List<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo> conteudo_;
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    public java.util.List<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo> getConteudoList() {
      return conteudo_;
    }
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    public java.util.List<? extends br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder> 
        getConteudoOrBuilderList() {
      return conteudo_;
    }
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    public int getConteudoCount() {
      return conteudo_.size();
    }
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo getConteudo(int index) {
      return conteudo_.get(index);
    }
    /**
     * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder getConteudoOrBuilder(
        int index) {
      return conteudo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEmissorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, emissor_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      if (!getHoraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hora_);
      }
      if (!getGrupoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, grupo_);
      }
      for (int i = 0; i < conteudo_.size(); i++) {
        output.writeMessage(5, conteudo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEmissorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, emissor_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      if (!getHoraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hora_);
      }
      if (!getGrupoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, grupo_);
      }
      for (int i = 0; i < conteudo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, conteudo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem other = (br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem) obj;

      boolean result = true;
      result = result && getEmissor()
          .equals(other.getEmissor());
      result = result && getData()
          .equals(other.getData());
      result = result && getHora()
          .equals(other.getHora());
      result = result && getGrupo()
          .equals(other.getGrupo());
      result = result && getConteudoList()
          .equals(other.getConteudoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMISSOR_FIELD_NUMBER;
      hash = (53 * hash) + getEmissor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + HORA_FIELD_NUMBER;
      hash = (53 * hash) + getHora().hashCode();
      hash = (37 * hash) + GRUPO_FIELD_NUMBER;
      hash = (53 * hash) + getGrupo().hashCode();
      if (getConteudoCount() > 0) {
        hash = (37 * hash) + CONTEUDO_FIELD_NUMBER;
        hash = (53 * hash) + getConteudoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatRabbitMQ.Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatRabbitMQ.Mensagem)
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Mensagem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.class, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConteudoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        emissor_ = "";

        data_ = "";

        hora_ = "";

        grupo_ = "";

        if (conteudoBuilder_ == null) {
          conteudo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          conteudoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Mensagem_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem build() {
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem result = new br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.emissor_ = emissor_;
        result.data_ = data_;
        result.hora_ = hora_;
        result.grupo_ = grupo_;
        if (conteudoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            conteudo_ = java.util.Collections.unmodifiableList(conteudo_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.conteudo_ = conteudo_;
        } else {
          result.conteudo_ = conteudoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem.getDefaultInstance()) return this;
        if (!other.getEmissor().isEmpty()) {
          emissor_ = other.emissor_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getHora().isEmpty()) {
          hora_ = other.hora_;
          onChanged();
        }
        if (!other.getGrupo().isEmpty()) {
          grupo_ = other.grupo_;
          onChanged();
        }
        if (conteudoBuilder_ == null) {
          if (!other.conteudo_.isEmpty()) {
            if (conteudo_.isEmpty()) {
              conteudo_ = other.conteudo_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureConteudoIsMutable();
              conteudo_.addAll(other.conteudo_);
            }
            onChanged();
          }
        } else {
          if (!other.conteudo_.isEmpty()) {
            if (conteudoBuilder_.isEmpty()) {
              conteudoBuilder_.dispose();
              conteudoBuilder_ = null;
              conteudo_ = other.conteudo_;
              bitField0_ = (bitField0_ & ~0x00000010);
              conteudoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConteudoFieldBuilder() : null;
            } else {
              conteudoBuilder_.addAllMessages(other.conteudo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object emissor_ = "";
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       */
      public java.lang.String getEmissor() {
        java.lang.Object ref = emissor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emissor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmissorBytes() {
        java.lang.Object ref = emissor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emissor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       */
      public Builder setEmissor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emissor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       */
      public Builder clearEmissor() {
        
        emissor_ = getDefaultInstance().getEmissor();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       */
      public Builder setEmissorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emissor_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hora_ = "";
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       */
      public java.lang.String getHora() {
        java.lang.Object ref = hora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHoraBytes() {
        java.lang.Object ref = hora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       */
      public Builder setHora(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hora_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       */
      public Builder clearHora() {
        
        hora_ = getDefaultInstance().getHora();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       */
      public Builder setHoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hora_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object grupo_ = "";
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       */
      public java.lang.String getGrupo() {
        java.lang.Object ref = grupo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grupo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGrupoBytes() {
        java.lang.Object ref = grupo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grupo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       */
      public Builder setGrupo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        grupo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       */
      public Builder clearGrupo() {
        
        grupo_ = getDefaultInstance().getGrupo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       */
      public Builder setGrupoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        grupo_ = value;
        onChanged();
        return this;
      }

      private java.util.List<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo> conteudo_ =
        java.util.Collections.emptyList();
      private void ensureConteudoIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          conteudo_ = new java.util.ArrayList<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo>(conteudo_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder> conteudoBuilder_;

      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public java.util.List<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo> getConteudoList() {
        if (conteudoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(conteudo_);
        } else {
          return conteudoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public int getConteudoCount() {
        if (conteudoBuilder_ == null) {
          return conteudo_.size();
        } else {
          return conteudoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo getConteudo(int index) {
        if (conteudoBuilder_ == null) {
          return conteudo_.get(index);
        } else {
          return conteudoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder setConteudo(
          int index, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConteudoIsMutable();
          conteudo_.set(index, value);
          onChanged();
        } else {
          conteudoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder setConteudo(
          int index, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder builderForValue) {
        if (conteudoBuilder_ == null) {
          ensureConteudoIsMutable();
          conteudo_.set(index, builderForValue.build());
          onChanged();
        } else {
          conteudoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder addConteudo(br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConteudoIsMutable();
          conteudo_.add(value);
          onChanged();
        } else {
          conteudoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder addConteudo(
          int index, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConteudoIsMutable();
          conteudo_.add(index, value);
          onChanged();
        } else {
          conteudoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder addConteudo(
          br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder builderForValue) {
        if (conteudoBuilder_ == null) {
          ensureConteudoIsMutable();
          conteudo_.add(builderForValue.build());
          onChanged();
        } else {
          conteudoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder addConteudo(
          int index, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder builderForValue) {
        if (conteudoBuilder_ == null) {
          ensureConteudoIsMutable();
          conteudo_.add(index, builderForValue.build());
          onChanged();
        } else {
          conteudoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder addAllConteudo(
          java.lang.Iterable<? extends br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo> values) {
        if (conteudoBuilder_ == null) {
          ensureConteudoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, conteudo_);
          onChanged();
        } else {
          conteudoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder clearConteudo() {
        if (conteudoBuilder_ == null) {
          conteudo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          conteudoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public Builder removeConteudo(int index) {
        if (conteudoBuilder_ == null) {
          ensureConteudoIsMutable();
          conteudo_.remove(index);
          onChanged();
        } else {
          conteudoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder getConteudoBuilder(
          int index) {
        return getConteudoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder getConteudoOrBuilder(
          int index) {
        if (conteudoBuilder_ == null) {
          return conteudo_.get(index);  } else {
          return conteudoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public java.util.List<? extends br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder> 
           getConteudoOrBuilderList() {
        if (conteudoBuilder_ != null) {
          return conteudoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(conteudo_);
        }
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder addConteudoBuilder() {
        return getConteudoFieldBuilder().addBuilder(
            br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.getDefaultInstance());
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder addConteudoBuilder(
          int index) {
        return getConteudoFieldBuilder().addBuilder(
            index, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.getDefaultInstance());
      }
      /**
       * <code>repeated .ChatRabbitMQ.Conteudo conteudo = 5;</code>
       */
      public java.util.List<br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder> 
           getConteudoBuilderList() {
        return getConteudoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder> 
          getConteudoFieldBuilder() {
        if (conteudoBuilder_ == null) {
          conteudoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder>(
                  conteudo_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          conteudo_ = null;
        }
        return conteudoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatRabbitMQ.Mensagem)
    }

    // @@protoc_insertion_point(class_scope:ChatRabbitMQ.Mensagem)
    private static final br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mensagem>
        PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mensagem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Mensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConteudoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatRabbitMQ.Conteudo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     */
    java.lang.String getTipo();
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     */
    com.google.protobuf.ByteString
        getTipoBytes();

    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>bytes corpo = 2;</code>
     */
    com.google.protobuf.ByteString getCorpo();

    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     */
    java.lang.String getNome();
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();
  }
  /**
   * Protobuf type {@code ChatRabbitMQ.Conteudo}
   */
  public  static final class Conteudo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatRabbitMQ.Conteudo)
      ConteudoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Conteudo.newBuilder() to construct.
    private Conteudo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Conteudo() {
      tipo_ = "";
      corpo_ = com.google.protobuf.ByteString.EMPTY;
      nome_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Conteudo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tipo_ = s;
              break;
            }
            case 18: {

              corpo_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Conteudo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Conteudo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.class, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder.class);
    }

    public static final int TIPO_FIELD_NUMBER = 1;
    private volatile java.lang.Object tipo_;
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORPO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString corpo_;
    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>bytes corpo = 2;</code>
     */
    public com.google.protobuf.ByteString getCorpo() {
      return corpo_;
    }

    public static final int NOME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nome_;
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTipoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tipo_);
      }
      if (!corpo_.isEmpty()) {
        output.writeBytes(2, corpo_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nome_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTipoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tipo_);
      }
      if (!corpo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, corpo_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nome_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo other = (br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo) obj;

      boolean result = true;
      result = result && getTipo()
          .equals(other.getTipo());
      result = result && getCorpo()
          .equals(other.getCorpo());
      result = result && getNome()
          .equals(other.getNome());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIPO_FIELD_NUMBER;
      hash = (53 * hash) + getTipo().hashCode();
      hash = (37 * hash) + CORPO_FIELD_NUMBER;
      hash = (53 * hash) + getCorpo().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatRabbitMQ.Conteudo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatRabbitMQ.Conteudo)
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.ConteudoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Conteudo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Conteudo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.class, br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tipo_ = "";

        corpo_ = com.google.protobuf.ByteString.EMPTY;

        nome_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.internal_static_ChatRabbitMQ_Conteudo_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo build() {
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo result = new br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo(this);
        result.tipo_ = tipo_;
        result.corpo_ = corpo_;
        result.nome_ = nome_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo.getDefaultInstance()) return this;
        if (!other.getTipo().isEmpty()) {
          tipo_ = other.tipo_;
          onChanged();
        }
        if (other.getCorpo() != com.google.protobuf.ByteString.EMPTY) {
          setCorpo(other.getCorpo());
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tipo_ = "";
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       */
      public java.lang.String getTipo() {
        java.lang.Object ref = tipo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTipoBytes() {
        java.lang.Object ref = tipo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       */
      public Builder setTipo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tipo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       */
      public Builder clearTipo() {
        
        tipo_ = getDefaultInstance().getTipo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       */
      public Builder setTipoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tipo_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString corpo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>bytes corpo = 2;</code>
       */
      public com.google.protobuf.ByteString getCorpo() {
        return corpo_;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>bytes corpo = 2;</code>
       */
      public Builder setCorpo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        corpo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>bytes corpo = 2;</code>
       */
      public Builder clearCorpo() {
        
        corpo_ = getDefaultInstance().getCorpo();
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatRabbitMQ.Conteudo)
    }

    // @@protoc_insertion_point(class_scope:ChatRabbitMQ.Conteudo)
    private static final br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Conteudo>
        PARSER = new com.google.protobuf.AbstractParser<Conteudo>() {
      public Conteudo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Conteudo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Conteudo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Conteudo> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.ProtoBuf.Conteudo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRabbitMQ_Mensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRabbitMQ_Conteudo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRabbitMQ_Conteudo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6src/main/java/br/ufs/dcomp/ChatRabbitM" +
      "Q/ProtoBuf.proto\022\014ChatRabbitMQ\"p\n\010Mensag" +
      "em\022\017\n\007emissor\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\022\014\n\004hor" +
      "a\030\003 \001(\t\022\r\n\005grupo\030\004 \001(\t\022(\n\010conteudo\030\005 \003(\013" +
      "2\026.ChatRabbitMQ.Conteudo\"5\n\010Conteudo\022\014\n\004" +
      "tipo\030\001 \001(\t\022\r\n\005corpo\030\002 \001(\014\022\014\n\004nome\030\003 \001(\tB" +
      "%\n\031br.ufs.dcomp.ChatRabbitMQB\010ProtoBufb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChatRabbitMQ_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRabbitMQ_Mensagem_descriptor,
        new java.lang.String[] { "Emissor", "Data", "Hora", "Grupo", "Conteudo", });
    internal_static_ChatRabbitMQ_Conteudo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatRabbitMQ_Conteudo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRabbitMQ_Conteudo_descriptor,
        new java.lang.String[] { "Tipo", "Corpo", "Nome", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
